config/routes.rb
Rails.application.routes.draw do
    resources :topics do
        resources :posts, except: [:index]
    end
    
    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]

    get 'about' => 'welcome#about'
  
    root 'welcome#index'
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
   belongs_to :topic
   has_many :comments, dependent: :destroy
   
   validates :title, length: { minimum: 5 }, presence: true
   validates :body, length: { minimum: 20 }, presence: true
   validates :topic, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/sponsored_post.rb
class SponsoredPost < ApplicationRecord
    belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :posts, dependent: :destroy
    
    validates :name, length: { minimum: 5 }, presence: true
    validates :description, length: { minimum: 15 }, presence: true
    validates :public, presence: true
end

app/models/user.rb
class User < ApplicationRecord
   before_save { self.email = email.downcase if email.present? }
   before_save { self.name = name.split(' ').map{|n| n.capitalize}.join(' ') if name.present?}

   validates :name, length: { minimum: 1, maximum: 100 }, presence: true
   validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
   validates :password, length: { minimum: 6 }, allow_blank: true
   validates :email,
             presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 254 }

   has_secure_password
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
      @post = Post.find(params[:id])
  end

  def new
     @topic = Topic.find(params[:topic_id])
     @post = Post.new
  end
  
   def create
     @post = Post.new
     @post.title = params[:post][:title]
     @post.body = params[:post][:body]
     @topic = Topic.find(params[:topic_id])
     @post.topic = @topic
     
     if @post.save
       flash[:notice] = "Post was saved."
       redirect_to [@topic, @post]
     else
       flash.now[:alert] = "There was an error saving the post. Please try again."
       render :new
     end
   end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
     @post = Post.find(params[:id])
     @post.title = params[:post][:title]
     @post.body = params[:post][:body]
 
     if @post.save
       flash[:notice] = "Post was updated."
       redirect_to [@post.topic, @post]
     else
       flash.now[:alert] = "There was an error saving the post. Please try again."
       render :edit
     end
  end
  
  def destroy
     @post = Post.find(params[:id])
     if @post.destroy
       flash[:notice] = "\"#{@post.title}\" was deleted successfully."
       redirect_to @post.topic
     else
       flash.now[:alert] = "There was an error deleting the post."
       render :show
     end
  end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def new
   end
 
   def create
     user = User.find_by(email: params[:session][:email].downcase)

     if user && user.authenticate(params[:session][:password])
       create_session(user)
       flash[:notice] = "Welcome, #{user.name}!"
       redirect_to root_path
     else
       flash.now[:alert] = 'Invalid email/password combination'
       render :new
     end
   end
 
   def destroy
     destroy_session(current_user)
     flash[:notice] = "You've been signed out, come back soon!"
     redirect_to root_path
   end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    def index
     @topics = Topic.all
    end
    
    def show
     @topic = Topic.find(params[:id])
    end

    def new
     @topic = Topic.new
    end
    
    def create
     @topic = Topic.new
     @topic.name = params[:topic][:name]
     @topic.description = params[:topic][:description]
     @topic.public = params[:topic][:public]
 
     if @topic.save!
       redirect_to @topic, notice: "Topic was saved successfully."
     else
       flash.now[:alert] = "Error creating topic. Please try again."
       render :new
     end
    end
    
    def edit
     @topic = Topic.find(params[:id])
    end
    
    def update
     @topic = Topic.find(params[:id])
 
     @topic.name = params[:topic][:name]
     @topic.description = params[:topic][:description]
     @topic.public = params[:topic][:public]
 
     if @topic.save
        flash[:notice] = "Topic was updated."
       redirect_to @topic
     else
       flash.now[:alert] = "Error saving topic. Please try again."
       render :edit
     end
    end
    
    def destroy
     @topic = Topic.find(params[:id])
 
     if @topic.destroy
       flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash.now[:alert] = "There was an error deleting the topic."
       render :show
     end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
   def new
     @user = User.new
   end
   
   def create
       
     @user = User.new
     @user.name = params[:user][:name]
     @user.email = params[:user][:email]
     @user.password = params[:user][:password]
     @user.password_confirmation = params[:user][:password_confirmation]
     
     if @user.save
       flash[:notice] = "Welcome to Bloccit #{@user.name}!"
       create_session(@user)
       redirect_to root_path
     else
       flash.now[:alert] = "There was an error creating your account. Please try again."
       render :new
     end
   end
   
   def confirm
     @user = User.new
     @user.name = params[:user][:name]
     @user.email = params[:user][:email]
     @user.password = params[:user][:password]
     @user.password_confirmation = params[:user][:password_confirmation]
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
  
  def contact
  end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def form_group_tag(errors, &block)
     css_class = 'form-group'
     css_class << ' has-error' if errors.any?
     
     content_tag :div, capture(&block), class: css_class
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def create_session(user)
     session[:user_id] = user.id
   end
 
   def destroy_session(user)
     session[:user_id] = nil
   end
 
   def current_user
     User.find_by(id: session[:user_id])
   end
end

app/helpers/sponsored_posts_helper.rb
module SponsoredPostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
   <div class="form-group">
      <% if post.errors.any? %>
      
     <div class="alert alert-danger">
         
       <h4><%= pluralize(post.errors.count, "error") %>.</h4>
       <ul>
         <% post.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
  
   <%= form_group_tag(post.errors[:title]) do %>
     <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
   <% end %>
 
   <%= form_group_tag(post.errors[:body]) do %>
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
   <% end %>
   
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/posts/edit.html.erb
 <h1>Edit Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
   </div>
 </div>

app/views/posts/new.html.erb
 <h1>New Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
   </div>
 </div>

app/views/posts/show.html.erb
 <h1><%= @post.title %></h1>
 
 <div class="row">
   <div class="col-md-8">
     <p><%= @post.body %></p>
   </div>
   <div class="col-md-4">
     <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>
     <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
   </div>
 </div>

app/views/topics/_form.html.erb
<%= form_for topic do |f| %>
   <div class="form-group">
      <% if topic.errors.any? %>
      
     <div class="alert alert-danger">
         
       <h4><%= pluralize(topic.errors.count, "error") %>.</h4>
       <ul>
         <% topic.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
  
   <%= form_group_tag(topic.errors[:name]) do %>
     <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: "Enter post title" %>
   <% end %>
 
   <%= form_group_tag(topic.errors[:description]) do %>
     <%= f.label :description %>
     <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
   <% end %>
   
   <div class="form-group">
      <%= f.label :public, class: 'checkbox' do %>
      <%= f.check_box :public %> Public topic<% end %>
   </div>
    <%= f.submit "Save", class: 'btn btn-success' %>
 <% end %>

app/views/topics/edit.html.erb
 <h1>Edit Topic</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { topic: @topic } %>
   </div>
 </div>

app/views/topics/index.html.erb
 <h1>Topics</h1>
 
 <div class="row">
   <div class="col-md-8">
     <% @topics.each do |topic| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to topic.name, topic %>
           </h4>
           <small>
             <%= topic.description %>
           </small>
         </div>
       </div>
     <% end %>
   </div>
   <div class="col-md-4">
     <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
   </div>
 </div>

app/views/topics/new.html.erb
<h1>New Topic</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { topic: @topic } %>
   </div>
 </div>

app/views/topics/show.html.erb
 <h1><%= @topic.name %></h1>
 
 <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
 <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
 
 <div class="row">
   <div class="col-md-8">
     <p class="lead"><%= @topic.description %></p>
     <% @topic.posts.each do |post| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to post.title, topic_post_path(@topic, post) %>
           </h4>
           <small>
             submitted <%= time_ago_in_words(post.created_at) %> ago <br>
             <%= post.comments.count %> Comments
           </small>
         </div>
       </div>
     <% end %>
      <%= link_to "New Sponsored Post", new_topic_sponsored_post_path(@topic), class: 'btn btn-success' %>
    <% @topic.sponsored_posts.each do |sponsored_post| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to sponsored_post.title, topic_sponsored_post_path(@topic, sponsored_post) %>
          </h4>
          <small>
            Price: $<%= sponsored_post.price %>
          </small>
        </div>
      </div>
    <% end %>
   </div>
   <div class="col-md-4">
     <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
     <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
   </div>
 </div>

app/views/users/confirm.html.erb
<h2>Sign Up Confirmation</h2>


<div class="row">
    <h4>Are you sure these values are correct?</h4>
    <div class="col-md-4">
        <h6>Email: <%= @user.email %></h6>
        <h6>Name: <%= @user.name %></h6>
    </div>
</div>

<div class="col-md-4">
<%= button_to "Yes", {controller: "users", action: "create", params: { user: params.require(:user).permit(:name, :email, :password, :password_confirmation).to_h }}, class: 'btn btn-success' %>
</div>

<div class="col-md-4">
<%= button_to "No", {controller: "users", action: "new"}, class: 'btn btn-failure', method: :get %>
</div>

app/views/users/confirmation.html.erb
<h2>Sign Up Confirmation</h2>

<h4>Are you sure these values are correct?</h4>

<div class="row">
    <div class="col-md-4">
        <h6>Email: <%= @user.email %></h6>
        <h6>Name: <%= @user.name %></h6>
    </div>
</div>

<div class="col-md-4">
<%= button_to "Yes", {controller: "users", action: "create", params: { user: params.require(:user).permit(:name, :email, :password, :password_confirmation).to_h }}, class: 'btn btn-success' %>
</div>

<%= button_to "No", {controller: "users", action: "new"}, class: 'btn btn-failure', method: :get %>

app/views/users/new.html.erb
<h2>Sign up</h2>
 
 <div class="row">
   <div class="col-md-8">
     <%= form_for @user, url: { action: :confirm } do |f| %>
 
       <% if @user.errors.any? %>
         <div class="alert alert-danger">
           <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
           <ul>
             <% @user.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
       <% end %>

       <%= form_group_tag(@user.errors[:name]) do %>
         <%= f.label :name %>
         <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
       <% end %>
       <%= form_group_tag(@user.errors[:email]) do %>
         <%= f.label :email %>
         <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password]) do %>
         <%= f.label :password %>
         <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password_confirmation]) do %>
         <%= f.label :password_confirmation %>
         <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
       <% end %>
       <div class="form-group">
         <%= f.submit "Sign up", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>